[tool.poetry]
name = "msys2-web"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
httpx = {extras = ["http2"], version = "^0.25.0"}
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
aiofiles = "^23.1.0"
jinja2 = "^3.1.2"
fastapi-etag = "^0.4.0"
gunicorn = "^21.0.1"
aiolimiter = "^1.0.0-beta.1"
pydantic = "^2.0.3"
zstandard = "^0.22.0"
MarkupSafe = "^2.1.1"

[tool.poetry.group.dev.dependencies]
reuse = "^2.1.0"
mypy = "1.7.1"
flake8 = "^6.0.0"
pytest = "^7.2.0"
requests = "^2.23.0"
respx = "^0.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
